/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mine.java.new.features.app;

import mine.java.new.features.list.LinkedList;

import static mine.java.new.features.utilities.StringUtils.join;
import static mine.java.new.features.utilities.StringUtils.split;
import static mine.java.new.features.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
