/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jnew.features.j9;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        System.out.println(WordUtils.capitalize(MessageUtils.getMessage()));
    }
}
